#!/bin/bash

if [[ $# -eq 1 ]]
	then
		counter=0
		while [ $counter -lt $1 ]; do
			touch file$[$counter+1]
			echo "I am file $[$counter+1]!" >> file$[$counter+1]
			counter=$[$counter+1]
			done
		echo "$1 files successfully created"	
		exit 0
	else
		echo "Incorrect number of arguments"
		echo "Expected 1; Received $#"
		exit 1
fi
